# Generated by Django 2.0.7 on 2018-07-27 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chat_vocab_t',
        ),
    ]
