# Generated by Django 2.0.6 on 2018-07-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Casenumber', models.CharField(max_length=30)),
                ('Date', models.DateTimeField()),
                ('Description', models.TextField()),
                ('LocationDescription', models.CharField(max_length=30)),
                ('Longtitude', models.FloatField()),
                ('Latitude', models.FloatField()),
                ('UpdateTime', models.DateTimeField()),
            ],
        ),
    ]
