# Generated by Django 2.0.7 on 2018-07-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_chat_vocab_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_vocab_t',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chat_vocab_t',
            name='side',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chat_vocab_t',
            name='vocab',
            field=models.CharField(max_length=50),
        ),
    ]
