# Generated by Django 2.0.7 on 2018-07-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='Latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='Longtitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='UpdateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
