# Generated by Django 2.0.7 on 2018-07-16 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180716_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crime_t',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
