# Generated by Django 2.0.7 on 2018-07-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180716_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime_t',
            name='created_by_user',
            field=models.BooleanField(default=True),
        ),
    ]
