# Generated by Django 2.0.7 on 2018-07-27 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180726_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chat_vocab_t',
        ),
    ]
