# Generated by Django 2.0.7 on 2018-07-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_chat_vocab_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_vocab_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('side', models.CharField(max_length=30)),
            ],
        ),
    ]
