# Generated by Django 2.0.7 on 2018-07-29 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180727_1504'),
    ]

    operations = [
    ]
