# Generated by Django 2.0.7 on 2018-07-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180730_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime_t',
            name='created_by_user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
